In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
l=range(1000)
%timeit [i**2 for i in l]

78 μs ± 5.22 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# CREATING ARRAYS


In [10]:
#one dimension
a=np.array([1,2,3,4])
print(a.ndim)

1


In [11]:
#two dimension
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [12]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
print(a.shape)

(4,)


In [14]:
print(b.shape)

(2, 3)


In [15]:
print(c.shape)

(2, 2, 2)


# FUNCTIONS FOR CREATING ARRAY

In [17]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


#using linspace

In [20]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [21]:
a=np.linspace(0,1,4)
print(a)

[0.         0.33333333 0.66666667 1.        ]


In [22]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [28]:
a=np.eye(5,5)
print(a)
print(np.diag(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


# BASIC DATA TYPES

In [29]:
a=np.arange(10)
print(a.dtype)

int64


In [30]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


# OTHER DATA TYPE

In [31]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [32]:
a=np.array([True,False])
print(a.dtype)

bool


In [34]:
a=np.array(['srivalli','mohi'])
print(a.dtype)#unicode string type(means which is the highest length of the code displays the that lenght only)

<U8


# INDEXING

In [36]:
a=np.arange(10)
print(a[5])

5


In [37]:
a=np.arange(2,20,2)
print(a[2])

6


In [39]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [40]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# SLICING

In [44]:
a=np.arange(10)
print(a)
print(a[1:8:2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


# COPIES & VIEWING

In [45]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)
print(np.shares_memory(a,b))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True


In [46]:
b[0]=10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [47]:
#dot copy(.copy)used for different memory spaces
a=np.arange(10)
b=a[::2].copy()#force copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# RANDOM NUMBER GENERATOR(like otp purpose)

In [49]:
a=np.random.randint(0,20,15)
print(a)

[17 19 10 18  8  8  0 11 16 19  8 16 17  6  0]


In [50]:
a=np.random.randint(0,9,4)
print(a)

[3 1 2 1]


In [51]:
a=np.random.randint(0,9,6)
print(a)

[6 2 8 6 1 2]


# ELEMENT WISE OPERATIONS

#BASIC OPERATIONS

In [52]:
a=np.array([1,2,3,4,5])
print(a+1)#add+1

[2 3 4 5 6]


In [55]:
print(a**2)#squares

[ 1  4  9 16 25]


In [54]:
print(a-b)

[ 1  0 -1 -2 -3]


# COMPARSION OPERATORS

In [57]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [58]:
print(a<b)

[ True False  True False]


In [59]:
print(a>b)

[False False False False]


# ARRAY WISE COMPARSIONS

In [61]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [62]:
print(np.array_equal(a,c))

True


# LOGICAL OPERATORS

In [63]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [65]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_and(a,b))

[ True False False False]


# ALL ARITHMETIC OPERATORS ELEMENTWISE

In [12]:
import numpy as np
b=np.ones(4)+1 #[2 2 2 2]
print("b=",b)

b= [2. 2. 2. 2.]


In [13]:
print(a*b)

[4. 4. 4. 4.]


In [14]:
print(a-b)

[0. 0. 0. 0.]


# BASIC REDUCTIONS

In [15]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [16]:
x=np.array([[1,2],[1,2]])
print(x)

[[1 2]
 [1 2]]


In [17]:
x.sum(axis=0)#column dimension

array([2, 4])

In [18]:
x.sum(axis=1)#row dimension

array([3, 3])

# OTHER REDUCTION

In [19]:
x=np.array([1,2,3,4])
print(np.sum(x))

10
